### ISSUE TITLE
请教下这个报错该怎么解决SyntaxError: unterminated string literal

### ISSUE THREAD

**Issue by tyhunter** [xjasonlyu/98tang_daysign#16]
Traceback (most recent call last):
  File "/ql/data/scripts/xjasonlyu_98tang_daysign/daysign.py", line 199, in <module>
    main()
  File "/ql/data/scripts/xjasonlyu_98tang_daysign/daysign.py", line 169, in main
    cookies = retrieve_cookies_from_fetch('FETCH_98TANG')
  File "/ql/data/scripts/xjasonlyu_98tang_daysign/daysign.py", line 137, in retrieve_cookies_from_fetch
    cookie_str = parse_fetch(os.getenv(env))['headers']['cookie']
  File "/ql/data/scripts/xjasonlyu_98tang_daysign/daysign.py", line 132, in parse_fetch
    exec(s, {
  File "<string>", line 7
    "sec-ch-ua": "\Not/A)Brand\;v=\99\, \Google Chrome\;v=\115\, \Chromium\;v=\115\",
                 ^
SyntaxError: unterminated string literal (detected at line 7)

复制出来的fech格式如下，变量名称FETCH_98TANG
fetch("https://www.sehuatang.net/plugin.php?id=dd_sign:index", {
  "headers": {
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
    "accept-language": "en,zh-CN;q=0.9,zh;q=0.8",
    "cache-control": "no-cache",
    "pragma": "no-cache",
    "sec-ch-ua": "\"Not/A)Brand\";v=\"99\", \"Google Chrome\";v=\"115\", \"Chromium\";v=\"115\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"macOS\"",
    "sec-fetch-dest": "document",
    "sec-fetch-mode": "navigate",
    "sec-fetch-site": "same-origin",
    "sec-fetch-user": "?1",
    "upgrade-insecure-requests": "1",
    "cookie": "******",
    "Referer": "https://www.sehuatang.net/forum.php?mod=viewthread&tid=1499862&extra=page%3D1",
    "Referrer-Policy": "strict-origin-when-cross-origin"
  },
  "body": null,
  "method": "GET"
});

**Comment by EdisonCh4n** [comment]
同样的报错，求大佬指导下

**Comment by fdxi2011** [comment]
大佬，请教一下，报这个错误是什么题：
## 开始执行... 2024-01-19 22:10:35

comment to: tid = 1808288, message = 不错。。。
Traceback (most recent call last):
  File "/ql/data/scripts/xjasonlyu_98tang_daysign/daysign.py", line 180, in main
    raw_html = daysign(cookies=cookies)
  File "/ql/data/scripts/xjasonlyu_98tang_daysign/daysign.py", line 102, in daysign
    soup = BeautifulSoup(r.text, 'xml')
  File "/usr/local/lib/python3.10/site-packages/bs4/__init__.py", line 250, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: xml. Do you need to install a parser library?
错误原因：Couldn't find a tree builder with the features you requested: xml. Do you need to install a parser library?
tg 服务的 bot_token 或者 user_id 未设置!!
取消推送

## 执行结束... 2024-01-19 22:10:40  耗时 5 秒
