### ISSUE TITLE
大佬，请教一下，报这个错误是怎么回事啊？

### ISSUE THREAD

**Issue by fdxi2011** [xjasonlyu/98tang_daysign#18]
大佬，请教一下，报这个错误是怎么回事啊？
## 开始执行... 2024-01-19 22:10:35

comment to: tid = 1808288, message = 不错。。。
Traceback (most recent call last):
  File "/ql/data/scripts/xjasonlyu_98tang_daysign/daysign.py", line 180, in main
    raw_html = daysign(cookies=cookies)
  File "/ql/data/scripts/xjasonlyu_98tang_daysign/daysign.py", line 102, in daysign
    soup = BeautifulSoup(r.text, 'xml')
  File "/usr/local/lib/python3.10/site-packages/bs4/__init__.py", line 250, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: xml. Do you need to install a parser library?
错误原因：Couldn't find a tree builder with the features you requested: xml. Do you need to install a parser library?
tg 服务的 bot_token 或者 user_id 未设置!!
取消推送

## 执行结束... 2024-01-19 22:10:40  耗时 5 秒

**Comment by fdxi2011** [comment]
> 需要 pip install lxml 一下

解决了，太感谢了！！
