### ISSUE TITLE
求助调用flaresolverr时出现TypeError: FlareSolverrHTTPClient.request() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by xueli12** [xjasonlyu/98tang_daysign#28]
调用作者大大的flaresolverr时出现了报错
client = FlareSolverrHTTPClient(url=flaresolverr_url,
                                                        proxy=proxy_url,
                                                        cookies=cookies,
                                                        http2=True)

  File "E:\python\98tang\flaresolverr.py", line 131, in __init__
    self.http_client = httpx.Client(
                       ^^^^^^^^^^^^^
TypeError: Client.__init__() got an unexpected keyword argument 'proxy'

**Comment by xueli12** [comment]
我把proxy这个参数删除后就出现下面这个错误：FlareSolverrHTTPClient.request() takes 2 positional arguments but 3 were given

**Comment by xjasonlyu** [comment]
不是很清楚你是怎么调用的

**Comment by xueli12** [comment]
> 不是很清楚你是怎么调用的
我没有青龙面板，我在您原来的代码的基础上，把main函数下面这里改了，cookies也改为了我自己的cookies的字典形式
    try:
        raw_html = daysign(
            cookies=cookies,
            flaresolverr_url='http://127.0.0.1:8191',
            flaresolverr_proxy='http://127.0.0.1:10809',
        )

**Comment by xueli12** [comment]
错误原因：Client.__init__() got an unexpected keyword argument 'proxy'
Traceback (most recent call last):
  File "E:\python\98tang\98tang_daysign-main (1)\98tang_daysign-main\daysign2.py", line 253, in main
    raw_html = daysign(
               ^^^^^^^^
  File "E:\python\98tang\98tang_daysign-main (1)\98tang_daysign-main\daysign2.py", line 58, in daysign
    with (FlareSolverrHTTPClient(url=flaresolverr_url,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\python\98tang\98tang_daysign-main (1)\98tang_daysign-main\flaresolverr.py", line 131, in __init__
    self.http_client = httpx.Client(
                       ^^^^^^^^^^^^^
TypeError: Client.__init__() got an unexpected keyword argument 'proxy'

**Comment by xjasonlyu** [comment]
不确定具体原因，也有可能是你httpx 或者 python版本太旧

**Comment by xueli12** [comment]
> 不确定具体原因，也有可能是你httpx 或者 python版本太旧

您是用什么版本的httpx，我的python版本是3.12

**Comment by xjasonlyu** [comment]
都是最新版本

**Comment by xueli12** [comment]
> 都是最新版本

我更新了httpx后，现在没报错了，但是出现以下提示：WARNING:root:Retry cf_clearance update after 10 seconds caused by error: Method not allowed.
WARNING:root:Retry cf_clearance update after 10 seconds caused by error: Method not allowed.

**Comment by xjasonlyu** [comment]
感觉是不是你的 flaresolverr有问题

**Comment by xueli12** [comment]
> 感觉是不是你的 flaresolverr有问题

![image](https://github.com/xjasonlyu/98tang_daysign/assets/51438016/72d6d692-3cd6-4d12-a68e-d9620c2691dd)
